#!/bin/bash
#SBATCH --time=00:05:00
#SBATCH --account=tutorial
#SBATCH --partition=tutorial
#SBATCH --nodes=2
#SBATCH --ntasks=16
#SBATCH --ntasks-per-node=8
#SBATCH --cpus-per-task=16
#SBATCH --gpus=16
#SBATCH --output="profiling-2n-cuda-aware-output.log"
#SBATCH --error="profiling-2n-cuda-aware-output.log"

unset SLURM_EXPORT_ENV 
unset SLURM_MEM_PER_NODE
unset SBATCH_EXPORT

export PMIX_MCA_psec=^munge
unset SLURM_CPU_BIND
unset OMPI_MCA_hwloc_base_binding_policy
unset OMPI_MCA_rmaps_base_mapping_policy

mkdir -p ../../source_code/mpi/output_profiler
profiler_output=../../source_code/mpi/output_profiler

#source ~/nways_multigpu/start_mpi_lustre.sh

mpirun  -np 16 --map-by ppr:4:socket nsys profile --trace=mpi,cuda,nvtx,ucx --stats=true --nic-metrics=true -o $profiler_output/jacobi_cuda_aware_mpi_report_2n.%q{OMPI_COMM_WORLD_RANK}  --force-overwrite true ./jacobi_cuda_aware_mpi -ny 32768 -skip_single_gpu


#mpirun -np 16 --map-by ppr:4:socket nsys profile --trace=mpi,cuda,nvtx,ucx  --stats=true --nic-metrics=true -o $profiler_output/jacobi_cuda_aware_mpi_report_2n_5k.%q{OMPI_COMM_WORLD_RANK}  --force-overwrite true ./jacobi_cuda_aware_mpi -ny 32768 -skip_single_gpu -niter 5000
